---

- name: iptables | IPv4 custom ports
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: iptables_ports
  notify: save iptables

- name: iptables | IPv6 custom ports
  iptables:
    chain: INPUT
    ip_version: ipv6
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: iptables_ports
  notify: save iptables
