---

- name: iptables | IPv4 custom ports
  iptables:
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: iptables_ports

- name: iptables | IPv6 custom ports
  iptables:
    ip_version: 6
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: iptables_ports
