---
# Reset firewall: clear rules and allow all traffic

- name: iptables | flush | policy ACCEPT
  iptables:
    ip_version: "{{ item.0 }}"
    chain: "{{ item.1 }}"
    policy: ACCEPT
  with_nested:
    - [ ipv4, ipv6 ]
    - [ INPUT, OUTPUT, FORWARD ]

- name: iptables | flush | clear rules
  iptables:
    ip_version: "{{ item.0 }}"
    table: "{{ item.1 }}"
    flush: yes
  with_nested:
    - [ ipv4, ipv6 ]
    - [ filter, nat ]
  when: iptables_has_ipv6_nat or item.0 != "ipv6" or item.1 != "nat"
