---

- name: iptables-persistent | package
  tags:
  - package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables-persistent

- name: iptables | enable IP forwarding
  tags:
  - sysctl
  when: "'gw' in group_names"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: iptables-persistent | service
  tags:
  - service
  service:
    name: netfilter-persistent
    state: started
    enabled: yes

