---

- name: iptables | persist | package
  tags:
  - package
  package:
    name: iptables-persistent

- name: iptables | persist | save file
  tags:
  - config
  file:
    path: "/etc/iptables/rules.{{ item }}"
    mode: 0640
  loop: [ v4, v6 ]

- name: iptables | persist | service
  tags:
  - service
  service:
    name: netfilter-persistent
    state: started
    enabled: yes

