---

# -A INPUT -p icmp -j ACCEPT
- name: iptables | IPv4 ping
  iptables:
    protocol: icmp
    jump: ACCEPT

# -A INPUT -p icmpv6 -j ACCEPT
- name: iptables | IPv6 ping
  iptables:
    ip_version: 6
    protocol: icmpv6
    jump: ACCEPT

# -A FORWARD -p icmpv6 -j ACCEPT
- name: iptables | IPv6 ping FORWARD
  iptables:
    ip_version: 6
    chain: FORWARD
    protocol: icmpv6
    jump: ACCEPT

