---

# -A INPUT -p icmp -j ACCEPT
- name: iptables | IPv4 ping
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
  when: iptables_enable_ping
  notify: iptables

# -A INPUT -p icmpv6 -j ACCEPT
- name: iptables | IPv6 ping
  iptables:
    ip_version: ipv6
    chain: INPUT
    protocol: icmpv6
    jump: ACCEPT
  when: iptables_enable_ping
  notify: iptables

# -A FORWARD -p icmpv6 -j ACCEPT
- name: iptables | IPv6 ping FORWARD
  iptables:
    ip_version: ipv6
    chain: FORWARD
    protocol: icmpv6
    jump: ACCEPT
  when: iptables_enable_ping
  notify: iptables

